

services:
  ripple-node:
    image: ghcr.io/flare-foundation/connected-chains-docker/rippled:3.1.1@sha256:a05f6215b47b2f12a535d0e0a5fde38054fb57b9070e488077a2f82e7df95043
    container_name: node-testnet-xrp
    restart: unless-stopped
    ports:
      - 15005:5005   # port_rpc_admin_local
      - 16006:6006   # port_ws_admin_local
      - 11235:51235 # port_peer
      - 11234:51234 # port_rpc_public
      - 11233:51233 # port_ws_public
      - 10051:50051 # port_grpc
    volumes:
      - ripple-testnet-data:/opt/ripple/.ripple/db
      - ./rippled.conf:/opt/ripple/.ripple/rippled.conf
      - ./validators.txt:/opt/ripple/.ripple/validators.txt

volumes:
  ripple-testnet-data:
