

services:
  ripple-node:
    image: ghcr.io/flare-foundation/connected-chains-docker/xrpl-deb:3.4.1@sha256:02d9a1f6cc364b9b022beafbfff0cc65126e589c017e00e6dbdb39167640f3ea
    container_name: node-testnet-xrp
    restart: unless-stopped
    ports:
      - 51235:51235 # port_peer
      - 11234:51234 # port_rpc_public
      - 11233:51233 # port_ws_public
    volumes:
      - ripple-testnet-data:/opt/xrpld/.xrpld/db
      - ./xrpld.cfg:/opt/xrpld/.xrpld/xrpld.cfg
      - ./validators.txt:/opt/xrpld/.xrpld/validators.txt

volumes:
  ripple-testnet-data:
