

services:
  ripple-node:
    image: ghcr.io/flare-foundation/connected-chains-docker/xrpl:3.2.1@sha256:9d10b59e790c69f5f9075195de9bb311348a747110ac1f8aeb34169f58322689
    container_name: node-testnet-xrp
    restart: unless-stopped
    ports:
      - 51235:51235 # port_peer
      - 11234:51234 # port_rpc_public
      - 11233:51233 # port_ws_public
    volumes:
      - ripple-testnet-data:/opt/xrpld/.xrpld/db
      - ./xrpld.cfg:/opt/xrpld/.xrpld/xrpld.cfg
      - ./validators.txt:/opt/xrpld/.xrpld/validators.txt

volumes:
  ripple-testnet-data:
