

services:
  dogecoin-node:
    image: flarefoundation/dogecoin:1.14.9-dless@sha256:a07f31426f946f2dc0f2f2eb1b293548994c38afc8ed5bf3d10e8101827e3a69
    container_name: node-testnet-doge
    restart: unless-stopped
    ports:
      - 44555:44555
      - 44556:44556
    volumes:
      - dogecoin-testnet-data:/opt/dogecoin/.dogecoin/db
      - ./dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf


volumes:
  dogecoin-testnet-data:
