

services:
  dogecoin-node:
    image: ghcr.io/flare-foundation/connected-chains-docker/dogecoind:v1.14.9@sha256:7314b6a42e626dbe125add01bf8aaff73935fb0373e60e0341013362f1dcd970
    container_name: node-testnet-doge
    restart: unless-stopped
    ports:
      - 44555:44555
      - 44556:44556
    volumes:
      - dogecoin-testnet-data:/opt/dogecoin/.dogecoin/db
      - ./dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf


volumes:
  dogecoin-testnet-data:
