name: fdc2-verifier-sgb

x-verifier: &verifier
  image: ghcr.io/flare-foundation/go-verifier-api:v0.1.0@sha256:a249c6cf1e37ca8b4c8249e0ec49de6334a89a3cc68969ca320e2d7e86c48506
  restart: unless-stopped
  healthcheck:
    test: ["CMD", "curl", "--fail", "--silent", "--show-error", "http://localhost:3120/api/health"]
    interval: 30s
    timeout: 5s
    retries: 3
    start_period: 10s

volumes:
  c-chain-indexer-database:

services:
  c-chain-indexer-db:
    image: mysql:9.5.0@sha256:57c892ddeb17e6c7dddf219914db017b2cf3e2797806a75424444b83622cc8ef
    profiles: [c-chain-indexer]
    env_file:
      - c-chain-indexer/database.env
    restart: unless-stopped
    volumes:
      - c-chain-indexer-database:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent --host localhost -p$${MYSQL_ROOT_PASSWORD}"]
      start_period: 60s
      start_interval: 2s
      timeout: 20s
      retries: 10

  c-chain-indexer:
    image: ghcr.io/flare-foundation/flare-system-c-chain-indexer:v2.0.2@sha256:4f5bb1e00b3e0b5f1dfb45670247505bdc7a0fee27df72f3e6bc57d5ac58a29f
    profiles: [c-chain-indexer]
    env_file:
      - c-chain-indexer/indexer.env
    restart: unless-stopped
    volumes:
      - ./c-chain-indexer/config.toml:/app/config.toml:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1h
    depends_on:
      c-chain-indexer-db:
        condition: service_healthy

  verifier_tee:
    <<: *verifier
    environment:
      SOURCE_ID: TEE
    env_file:
      - verifier.env
      - tee.env
    ports:
      - "9901:3120"

  verifier_xrp:
    <<: *verifier
    env_file:
      - verifier.env
      - xrp.env
    ports:
      - "9902:3120"
