

services:
  bitcoin-node:
    image: ghcr.io/flare-foundation/connected-chains-docker/bitcoind:v30.0@sha256:597de43e5354326449af50b2d60484344ad6208ed3f81be74373cdd7f83d3e6b
    container_name: node-testnet-btc
    restart: unless-stopped
    ports:
      - 18332:18332
      - 18333:18333
    volumes:
      - bitcoin-testnet-data:/opt/bitcoin/.bitcoin/db
      - ./bitcoin.conf:/opt/bitcoin/.bitcoin/bitcoin.conf

volumes:
  bitcoin-testnet-data:
