

services:
  bitcoin-node:
    image: flarefoundation/bitcoin:30.0-dless@sha256:6e47b8d293fd1ea96772e641c53b534b7ec94504d83188b689392259816d7ca4
    container_name: node-testnet-btc
    restart: unless-stopped
    ports:
      - 18332:18332
      - 18333:18333
    volumes:
      - bitcoin-testnet-data:/opt/bitcoin/.bitcoin/db
      - ./bitcoin.conf:/opt/bitcoin/.bitcoin/bitcoin.conf

volumes:
  bitcoin-testnet-data:
