services:
  evm-verifier:
    image: ghcr.io/flare-foundation/evm-verifier:v1.0.3
    container_name: evm-verifier
    restart: unless-stopped
    ports:
      - 9800:9800
    env_file:
      - verifier.env
