

services:
  bitcoin-node:
    image: flarefoundation/bitcoin:30.0-dless@sha256:6e47b8d293fd1ea96772e641c53b534b7ec94504d83188b689392259816d7ca4
    container_name: node-mainnet-btc
    restart: unless-stopped
    ports:
      - 8332:8332
      - 8333:8333
    volumes:
      - bitcoin-mainnet-data:/opt/bitcoin/.bitcoin/db
      - ./bitcoin.conf:/opt/bitcoin/.bitcoin/bitcoin.conf

volumes:
  bitcoin-mainnet-data:
